version: '3.7'
services:
  app:
    image: ddzuba/smarthome_backend
    container_name: app
    ports:
      - 8080:8080
    volumes:
      - .:/workspace
      - c:/TEMPerHUM:/workspace/temperum
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://smarthome:smarthome@db/smarthome"
    
  db:
    image: postgres:14
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=smarthome
      - POSTGRES_PASSWORD=smarthome
      - POSTGRES_DB=smarthome
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: